name: Build and Upload APK to Firebase

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'  # Specify Java distribution

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.4'


    - name: Verify Flutter Installation
      run: flutter doctor

    - name: Build APK
      run: flutter build apk --release

    - name: Verify APK existence
      run: |
        if [ -f build/app/outputs/flutter-apk/app-release.apk ]; then
          echo "APK found."
          ls -lh build/app/outputs/flutter-apk/app-release.apk
        else
          echo "APK not found in expected directory."
          exit 1
        fi

    - name: Install Firebase CLI
      run: curl -sL https://firebase.tools | bash

    - name: Check Firebase CLI Version
      run: firebase --version

    - name: Upload APK to Firebase App Distribution
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      run: |
        firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
          --app 1:506379882405:android:496c6cdc204790c5e6e24c \
          --groups "testers" \
          --release-notes "Automated build from GitHub Actions"
